# Bitwarden Android CredentialProviderService component.
PROVIDER='com.x8bit.bitwarden/com.x8bit.bitwarden.Autofill.CredentialProviderService'
AUTOFILL_PROVIDER='com.x8bit.bitwarden/com.x8bit.bitwarden.Autofill.AutofillService'
